version: 2

sources:
  - name: staging
    database: endless-bonus-375606
    schema: ext_trips_data_all

    tables:
      - name: green_trips_all
      - name: yellow_trips_all
      - name: fhv_trips_all